name: Build & Deploy VitePress + JupyterLite to GitHub Pages v10

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # needed by peaceiris/actions-gh-pages

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-vitepress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Build VitePress
        run: npm run build
      - name: Show VitePress output
        run: |
          echo "VitePress dist:"; find docs/.vitepress/dist -maxdepth 2 -type f | sed -n '1,120p'
      - name: Upload VitePress artifact
        uses: actions/upload-artifact@v4
        with:
          name: vitepress-dist
          path: docs/.vitepress/dist
   
  build-jupyterlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JupyterLite toolchain (pin to JL4 era)
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip wheel
          pip install \
            "jupyterlite-core>=0.6,<0.7" \
            "jupyterlite-pyodide-kernel>=0.6,<0.7" \
            "jupyter-server>=2.14,<3" \
            "jupyterlab_server>=2.27,<3"
          python - <<'PY'
          import jupyterlite_core, jupyterlite_pyodide_kernel, jupyter_server
          print("JL core", jupyterlite_core.__version__,
                "pyodide-kernel", jupyterlite_pyodide_kernel.__version__,
                "jupyter-server", jupyter_server.__version__)
          PY
          jupyter lite --version

      - name: Pick a reachable Pyodide mirror
        id: pickpyodide
        shell: bash
        run: |
          set -euo pipefail
          CANDIDATES=(
            "https://cdn.jsdelivr.net/pyodide/v0.26.2/full"
            "https://github.com/pyodide/pyodide/releases/download/0.26.2/pyodide-0.26.2.tar.bz2"
            "https://cdn.jsdelivr.net/pyodide/v0.25.1/full"
          )
          for U in "${CANDIDATES[@]}"; do
            # For GitHub releases, check differently
            if [[ "$U" == *"github.com"* ]]; then
              if curl -sIf "$U" | head -n 1 | grep -q "200\|302"; then
                echo "Using Pyodide from GitHub releases: ${U}"
                echo "url=${U}" >> "$GITHUB_OUTPUT"
                exit 0
              fi
            else
              # For CDN URLs, check for pyodide.js
              if curl -sIf -m 10 "${U}/pyodide.js" | head -n 1 | grep -q "200"; then
                echo "Using Pyodide mirror: ${U}"
                echo "url=${U}" >> "$GITHUB_OUTPUT"
                exit 0
              fi
            fi
          done
          echo "No Pyodide mirror reachable - trying default"
          echo "url=https://cdn.jsdelivr.net/pyodide/v0.26.2/full" >> "$GITHUB_OUTPUT"

      - name: Build JupyterLite
        env:
          JUPYTERLITE_PYODIDE_URL: ${{ steps.pickpyodide.outputs.url }}
        run: |
          set -euxo pipefail
          echo "Using Pyodide URL: ${JUPYTERLITE_PYODIDE_URL}"
          echo "Contents before build:"
          find jupyterlite/contents -maxdepth 3 -type f \( -name "*.ipynb" -o -name "*.py" \) || true

          jupyter lite build \
            --contents ./jupyterlite/contents \
            --output-dir dist/jupyterlite \
            --debug

          echo "Built JupyterLite tree (first 120 files):"
          find dist/jupyterlite -maxdepth 3 -type f | sed -n '1,120p'

          # Kernel + app checks
          test -f dist/jupyterlite/index.html
          test -f dist/jupyterlite/pyodide/pyodide.js
          test -f dist/jupyterlite/lab/index.html || \
          test -f dist/jupyterlite/retro/index.html || \
          test -f dist/jupyterlite/tree/index.html || \
          (echo "No known app entry (lab/retro/tree) found under dist/jupyterlite"; exit 1)

      - name: Upload JupyterLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: jupyterlite-dist
          path: dist/jupyterlite

