name: Build & Deploy VitePress + JupyterLite to GitHub Pages v12

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # needed by peaceiris/actions-gh-pages

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-vitepress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Build VitePress
        run: npm run build
      - name: Show VitePress output
        run: |
          echo "VitePress dist:"; find docs/.vitepress/dist -maxdepth 2 -type f | sed -n '1,120p'
      - name: Upload VitePress artifact
        uses: actions/upload-artifact@v4
        with:
          name: vitepress-dist
          path: docs/.vitepress/dist
   
  build-jupyterlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JupyterLite toolchain (pin to JL4 era)
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip wheel
          pip install \
            "jupyterlite-core>=0.6,<0.7" \
            "jupyterlite-pyodide-kernel>=0.6,<0.7" \
            "jupyter-server>=2.14,<3" \
            "jupyterlab_server>=2.27,<3"
          python - <<'PY'
          import jupyterlite_core, jupyterlite_pyodide_kernel, jupyter_server
          print("JL core", jupyterlite_core.__version__,
                "pyodide-kernel", jupyterlite_pyodide_kernel.__version__,
                "jupyter-server", jupyter_server.__version__)
          PY
          jupyter lite --version

      - name: Download and cache Pyodide
        run: |
          set -euxo pipefail
          
          # Download from GitHub releases (more reliable than CDN)
          PYODIDE_VERSION="0.26.2"
          PYODIDE_URL="https://github.com/pyodide/pyodide/releases/download/${PYODIDE_VERSION}/pyodide-${PYODIDE_VERSION}.tar.bz2"
          
          echo "Downloading Pyodide ${PYODIDE_VERSION} from GitHub releases..."
          curl -L -o pyodide.tar.bz2 "${PYODIDE_URL}"
          
          echo "Extracting Pyodide..."
          tar -xjf pyodide.tar.bz2
          
          echo "Extracted structure:"
          ls -la
          find pyodide -maxdepth 2 -type f | head -20
          
          echo "Pyodide downloaded successfully"

      - name: Build JupyterLite with local Pyodide
        run: |
          set -euxo pipefail
          
          echo "Contents before build:"
          find jupyterlite/contents -maxdepth 3 -type f \( -name "*.ipynb" -o -name "*.py" \) || true

          # Point to local Pyodide (the extracted 'pyodide' directory)
          jupyter lite build \
            --contents ./jupyterlite/contents \
            --output-dir dist/jupyterlite \
            --pyodide ./pyodide \
            --debug

          echo "Built JupyterLite tree (first 120 files):"
          find dist/jupyterlite -maxdepth 3 -type f | sed -n '1,120p'

          # Kernel + app checks
          test -f dist/jupyterlite/index.html
          test -f dist/jupyterlite/pyodide/pyodide.js
          test -f dist/jupyterlite/lab/index.html || \
          test -f dist/jupyterlite/retro/index.html || \
          test -f dist/jupyterlite/tree/index.html || \
          (echo "No known app entry (lab/retro/tree) found under dist/jupyterlite"; exit 1)

      - name: Upload JupyterLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: jupyterlite-dist
          path: dist/jupyterlite